apiVersion: v1
kind: ConfigMap
metadata:
  name: brainwalk-backend-config
  namespace: default
data:
  TIME_ZONE: Asia/Seoul
  
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb-service:3306/rememberv1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"

  SPRING_CLOUD_AWS_REGION_STATIC: "ap-northeast-2"
  SPRING_CLOUD_AWS_CREDENTIALS_INSTANCE_PROFILE: "false"

  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: "5000"

  MYBATIS_CONFIGURATION_LOG_IMPL: "org.apache.ibatis.logging.stdout.StdOutImpl"

  LOGGING_LEVEL_ROOT: "info"
  LOGGING_LEVEL_COM_REMEMBERME_DUNOESANCHAEG_MAPPER: "debug"

  KAKAO_REDIRECT_URI: "https://brainwalk.click/kakao-auth"

  COOKIE_DOMAIN: ".brainwalk.click"
  COOKIE_SECURE: "true"
  COOKIE_SAME_SITE: "None"

  APP_CORS_ALLOWED_ORIGINS: "https://brainwalk.click,http://localhost:5173"